#!/usr/bin/env python3
"""Smoke test for AfrekaOS language mode (Task 006A).

Validates app.language_mode and builds grounded-prompt previews for each
supported language. Does NOT call the model. Does NOT call the internet.
Standard library only. Writes previews under
artifacts/eval/task-006A-language-mode/.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from app import language_mode as lm  # noqa: E402
from app import prompt_context  # noqa: E402

OUT_DIR = REPO_ROOT / "artifacts" / "eval" / "task-006A-language-mode"
DEFAULT_QUESTION = (
    "A small shop has lower sales than usual, two fast-moving items are out of "
    "stock, the supplier delivery is delayed, and more customers are asking for "
    "credit. Give a short operating checklist."
)

# Maps language code -> preview filename stem.
FILENAMES = {
    "en": "english-grounded-prompt.txt",
    "yo": "yoruba-grounded-prompt.txt",
    "ha": "hausa-grounded-prompt.txt",
    "sw": "swahili-grounded-prompt.txt",
    "pcm": "pidgin-grounded-prompt.txt",
    "fr": "french-grounded-prompt.txt",
}


def main() -> int:
    failures: list[str] = []

    # 1. Validate the registry.
    langs = lm.get_supported_languages()
    expected = {"en", "yo", "ha", "sw", "pcm", "fr"}
    if set(langs.keys()) != expected:
        failures.append(
            f"language set mismatch: got {sorted(langs.keys())}, expected {sorted(expected)}"
        )
    else:
        print(f"[ok] all six languages present: {sorted(langs.keys())}")

    # 2. Validate fallback.
    if lm.normalize_language_code("zz") != "en":
        failures.append("unknown code did not fall back to English")
    else:
        print("[ok] unknown code falls back to English")
    if lm.normalize_language_code("yoruba") != "yo":
        failures.append("alias 'yoruba' did not normalize to 'yo'")
    else:
        print("[ok] alias 'Yoruba' -> 'yo'")

    # 3. Build prompt previews for each language and check required content.
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    delimiter = prompt_context.FINAL_GUIDANCE_DELIMITER
    for code in sorted(expected):
        label = lm.get_language_label(code)
        prompt = prompt_context.build_grounded_prompt(
            DEFAULT_QUESTION, language=code
        )
        # Checks.
        if label not in prompt:
            failures.append(f"{code}: prompt missing label '{label}'")
        if delimiter not in prompt:
            failures.append(f"{code}: prompt missing delimiter")
        if "cloud translation" not in prompt.lower():
            failures.append(f"{code}: prompt missing no-cloud-translation instruction")
        if "accounting" not in prompt.lower() or "banking" not in prompt.lower():
            failures.append(f"{code}: prompt missing operational boundary")
        # Save preview.
        fname = FILENAMES.get(code, f"{code}-grounded-prompt.txt")
        (OUT_DIR / fname).write_text(prompt, encoding="utf-8")
        print(f"[ok] {code} ({label}): preview written to {fname}")

    # 4. Write a short notes file.
    notes = OUT_DIR / "language-mode-notes.md"
    notes.write_text(
        "# Language Mode Preview Notes (Task 006A)\n\n"
        f"- Generated by: scripts/smoke_language_mode.py\n"
        f"- Languages: {', '.join(sorted(expected))}\n"
        f"- Default: {lm.DEFAULT_LANGUAGE}\n"
        f"- Cloud translation: False\n"
        f"- Retrieval corpus: English (this version)\n"
        f"- Each preview is a grounded prompt for the default Daily Advisor "
        f"question in the selected response language.\n",
        encoding="utf-8",
    )
    print(f"[ok] notes written to language-mode-notes.md")

    if failures:
        print("\nLANGUAGE MODE SMOKE TEST FAILED:")
        for f in failures:
            print(f"  - {f}")
        return 1

    print("\nLANGUAGE MODE SMOKE TEST PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
